# Portfolio Environment Configuration

name: "PortfolioEnv"

# Initial conditions
initial_balance: 100000.0

# Transaction costs
transaction_cost: 0.001  # 0.1% per trade

# Action space
action_type: "continuous"  # Options: discrete, continuous

# Reward function
reward_type: "log_utility"  # Options: log_utility, sharpe, total_return

# Risk aversion (for utility-based rewards)
risk_aversion: 2.0

# Constraints
max_weight: 1.0  # Maximum weight per asset
min_weight: 0.0  # Minimum weight per asset
allow_shorting: false

# Rebalancing
rebalance_freq: 1  # Rebalance every N days (1 = daily)

# Features included in state
state_features:
  - current_weights
  - asset_returns
  - volatility
  - previous_weights
  - regime
  - vix
  - portfolio_value
  - cash_weight

# Episode configuration
max_episode_steps: null  # null = use full dataset
