# Training Configuration

# Total training steps
total_timesteps: 200000

# Evaluation
eval_freq: 5000  # Evaluate every N steps
eval_episodes: 5  # Number of episodes per evaluation

# Logging
log_freq: 1000  # Log metrics every N steps
save_freq: 10000  # Save model every N steps

# Parallel environments (for on-policy algorithms)
n_envs: 4

# Early stopping
early_stopping:
  enabled: true
  patience: 10  # Stop if no improvement for N evaluations
  min_delta: 0.01  # Minimum improvement threshold

# Learning rate schedule
lr_schedule:
  type: "constant"  # Options: constant, linear, exponential
  initial: 3.0e-4
  final: 1.0e-5

# Checkpointing
checkpoint:
  save_best: true
  save_last: true
  metric: "eval_return"  # Metric to determine best model
