# SAC Agent Configuration

name: "SAC"
type: "continuous"

# Network architecture
hidden_dims:
  - 256
  - 256

# Learning parameters
learning_rate: 3.0e-4
gamma: 0.99  # Discount factor
tau: 0.005  # Soft update coefficient

# Temperature (entropy) parameter
alpha: 0.2
auto_tune_alpha: true

# Replay buffer
buffer_capacity: 1000000
batch_size: 256

# Training
update_freq: 1  # Update every N environment steps
gradient_steps: 1  # Gradient steps per update

# Exploration
initial_random_steps: 1000
